# Defaults
spec:
  destination:
    server: https://kubernetes.default.svc
cluster:
  name: "in-cluster"
  awsRegion: "ap-southeast-2"
  clusterAutoscaler:
    namespace: "kube-system"

# crossplane
kubernetes:
  enabled: false
  inCluster: false
  connectionSecretName:
  externalSecretName:

# crossplane dep
crossplane:
  args:
    - "--debug"
