---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: jk8s-github-repo
spec:

  compositeTypeRef:
    apiVersion: jk8s.io/v1beta1
    kind: XGitHubRepo

  patchSets:
    - name: common-parameters
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.parameters.name"

  resources:

    - name: repo
      base:
        apiVersion: repositories.github.crossplane.io/v1alpha1
        kind: Repository
        spec:
          deletionPolicy: Orphan
      patches:
        - type: PatchSet
          patchSetName: common-parameters
          # The GitHub Provider uses the crossplane.io/external name
          # as the name of the repo itself
        - fromFieldPath: "spec.parameters.name"        
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
        - fromFieldPath: "spec.parameters.owner"
          toFieldPath: "spec.forProvider.owner"
        - fromFieldPath: "spec.parameters.org"
          toFieldPath: "spec.forProvider.org"
        - fromFieldPath: "spec.parameters.private"
          toFieldPath: "spec.forProvider.private"
        - fromFieldPath: "spec.parameters.visibility"
          toFieldPath: "spec.forProvider.visibility"
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.gitUrl
          toFieldPath: status.gitURL
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.htmlUrl
          toFieldPath: status.htmlURL
