---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgithubrepos.jk8s.io
spec:
  group: jk8s.io
  names:
    kind: XGitHubRepo
    plural: xgithubrepos
  versions:
  - name: v1beta1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    description: Name of the GitHub Repo
                    type: string       
                  owner: 
                    description: Owner of the GitHub Repo
                    type: string       
                  org: 
                    description: Organization to add the GitHub Repo to
                    type: string    
                  private:
                    description: Is the repo private
                    type: boolean
                    default: true
                  visibility:
                    description: Whether the repo is public or private
                    type: string    
                    enum: [public, private]
                    default: private
                  templateRef:
                    description: "The template repo to base this new repo on (format: owner/repo)"
                    type: string
                required:
                  - name
                  - owner
            required:
              - parameters
          status:
            type: object
            properties:
              gitURL:
                type: string
              htmlURL:
                type: string
