apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hosts:
    - "kiali.{{ .Values.dns.fqdn }}"
  gateways:
    - istio-ingress/ingress-gateway
  http:
    - route:
        - destination:
            host: kiali
            port:
              number: 20001
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kiali
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  host: kiali
  trafficPolicy:
    tls:
      mode: DISABLE
---

