---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: amazon-rds-cluster
  labels:
    provider: aws
    service: rds
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: jk8s.io/v1beta1
    kind: XRDSCluster

  patchSets:
    - name: common-parameters
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.parameters.environment"
          toFieldPath: "spec.providerConfigRef.name"

  resources:
    - name: dbcluster
      base:
        apiVersion: rds.aws.crossplane.io/v1alpha1
        kind: DBCluster
        spec:
          forProvider:
            autogeneratePassword: true
            engine: aurora-postgresql
            masterUsername: postgres
            masterUserPasswordSecretRef:
              namespace: crossplane-system
              name: PATCHED
              key: password
            databaseName: postgres
            skipFinalSnapshot: true
            dbClusterParameterGroupNameSelector:
              matchControllerRef: true
              matchLabels:
                engine: aurora-postgresql
            applyImmediately: true
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            vpcSecurityGroupIDSelector:
              matchControllerRef: true
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - type: PatchSet
          patchSetName: common-parameters      
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.environment
              - fromFieldPath: spec.parameters.name
            strategy: string
            string:
              fmt: "%s-%s-rds-master-user"
          toFieldPath: spec.forProvider.masterUserPasswordSecretRef.name
          policy:
            fromFieldPath: Required
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.environment
              - fromFieldPath: spec.parameters.name
            strategy: string
            string:
              fmt: "%s-%s-rds-connection"
          toFieldPath: spec.writeConnectionSecretToRef.name
          policy:
            fromFieldPath: Required
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.dbClusterIdentifier
          toFieldPath: status.dbClusterIdentifier
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.endpoint
          toFieldPath: status.endpoint
        - type: ToCompositeFieldPath
          fromFieldPath: spec.writeConnectionSecretToRef.name
          toFieldPath: status.connectionSecretName

    - name: dbinstance
      base:
        apiVersion: rds.aws.crossplane.io/v1alpha1
        kind: DBInstance
        spec:
          forProvider:
            dbInstanceClass: db.t4g.medium
            engine: aurora-postgresql
            dbClusterIdentifier: PATCHED
      patches:
        - type: PatchSet
          patchSetName: common-parameters      
        - fromFieldPath: "status.dbClusterIdentifier"
          toFieldPath: "spec.forProvider.dbClusterIdentifier"

    - name: dbclusterparametergroup
      base:
        apiVersion: rds.aws.crossplane.io/v1alpha1
        kind: DBClusterParameterGroup
        metadata:
          labels:
            engine: aurora-postgresql
        spec:
          forProvider:
            dbParameterGroupFamily: aurora-postgresql12
            description: "aurora-postgresql-db-parameters"
      patches:
        - type: PatchSet
          patchSetName: common-parameters      

    - name: dbsubnetgroup
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: DBSubnetGroup
        metadata:
          labels:
        spec:
          forProvider:
            description: "RDS Cluster Subnet Group"
            subnetIdSelector:
              matchLabels:
                type: subnet
                visibility: isolated
      patches:
        - type: PatchSet
          patchSetName: common-parameters      
        - fromFieldPath: "spec.parameters.vpcName"
          toFieldPath: "spec.forProvider.subnetIdSelector.matchLabels.vpc"
        - fromFieldPath: "spec.parameters.environment"
          toFieldPath: "spec.forProvider.subnetIdSelector.matchLabels.environment"

    - name: vpcsecuritygroup
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: SecurityGroup
        metadata:
          labels:
        spec:
          forProvider:
            groupName: PATCHED
            description: "RDS Cluster Security Group"
            vpcIdSelector:
              matchLabels:
                vpcName: PATCHED
            ingress:
              - ipProtocol: tcp
                fromPort: 5432
                toPort: 5432
                ipRanges:
                  - cidrIp: 10.20.0.0/18
                  - cidrIp: 10.24.0.0/18
                  - cidrIp: 10.28.0.0/18
      patches:
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: "spec.parameters.vpcName"
          toFieldPath: "spec.forProvider.groupName"
          transforms:
            - type: string
              string:
                fmt: "rds-%s"
        - fromFieldPath: "spec.parameters.vpcName"
          toFieldPath: "spec.forProvider.vpcIdSelector.matchLabels.vpcName"
        - fromFieldPath: "spec.parameters.environment"
          toFieldPath: "spec.forProvider.vpcIdSelector.matchLabels.environment"

    - name: rdssecret
      base:
        apiVersion: secretsmanager.aws.crossplane.io/v1alpha1
        kind: Secret
        spec:
          forProvider:
            description: "RDS Connect Secret"
            stringSecretRef:
              namespace: crossplane-system
      patches:
        - type: PatchSet
          patchSetName: common-parameters
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.environment
              - fromFieldPath: spec.parameters.name
            strategy: string
            string:
              fmt: "%s-%s-rds-connection"
          toFieldPath: spec.forProvider.stringSecretRef.name
          policy:
            fromFieldPath: Required
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: status.rdsSecretName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.rdsSecretARN

