---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrdsclusters.jk8s.io
spec:
  group: jk8s.io
  names:
    kind: XRDSCluster
    plural: xrdsclusters
  connectionSecretKeys:
    - endpoint
    - username
    - password
    - port
    - db
  versions:
  - name: v1beta1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    description: Name of the RDS Cluster
                    type: string
                  region:
                    description: Region for the RDS Cluster
                    type: string       
                    enum: ["ap-southeast-2"]   
                    default: ap-southeast-2
                  environment:
                    description: The deployment environment
                    type: string
                  vpcName:
                    description: VPC to associate with this RDS cluster
                    type: string
                required:
                  - name
                  - region
                  - environment
                  - vpcName
            required:
              - parameters

          status:
            type: object 
            properties:
              dbClusterIdentifier:
                type: string
              rdsSecretName:
                type: string
              rdsSecretARN:
                type: string
              endpoint:
                type: string
