---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: jk8s-cluster
spec:
  compositeTypeRef:
    apiVersion: jk8s.io/v1beta1
    kind: XCluster

  patchSets:
    - name: common-parameters
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.parameters.region"
        - fromFieldPath: "spec.parameters.environment"
          toFieldPath: "spec.parameters.environment"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.parameters.name"            

  resources:

    - name: cluster-vpc
      base:
        apiVersion: aws.jk8s.io/v1beta1
        kind: XClusterVPC
      patches:    
        - type: PatchSet
          patchSetName: common-parameters

    - name: hosted-zone
      base:
        apiVersion: jk8s.io/v1beta1
        kind: XHostedZone
      patches:    
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: "spec.parameters.fqdn"
          toFieldPath: "spec.parameters.fqdn"
        - type: ToCompositeFieldPath
          fromFieldPath: status.zoneID
          toFieldPath: status.zoneID
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.delegationSet.nameServers
          toFieldPath: status.delegationSet.nameServers

    - name: hosted-zone-delegation
      base:
        apiVersion: route53.aws.crossplane.io/v1alpha1
        kind: ResourceRecordSet
        spec:
          forProvider:
            type: NS
      patched:
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: status.delegationSet.nameServers
          toFieldPath: spec.forProvider.resourceRecords
        - fromFieldPath: spec.parameters.environment
          toFieldPath: spec.forProvider.zoneIdSelector.matchLabels.environment
    
    - name: rds-cluster
      base:
        apiVersion: jk8s.io/v1beta1
        kind: XRDSCluster
        spec:
          parameters:
            name: PATCHED
      patches:
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.parameters.vpcName"
        - fromFieldPath: spec.parameters.name
          toFieldPath: spec.parameters.name
        - type: ToCompositeFieldPath
          fromFieldPath: status.rdsSecretName
          toFieldPath: status.rdsSecretName
        - type: ToCompositeFieldPath
          fromFieldPath: status.endpoint
          toFieldPath: status.rdsEndpoint

    - name: eks-cluster
      base:
        apiVersion: aws.jk8s.io/v1beta1
        kind: XEKSCluster
      patches:    
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.parameters.vpcName"
        - fromFieldPath: "spec.parameters.fqdn"
          toFieldPath: "spec.parameters.fqdn"
        - fromFieldPath: "status.zoneID"
          toFieldPath: "spec.parameters.hostedZoneID"
        - fromFieldPath: "status.rdsEndpoint"
          toFieldPath: "spec.parameters.rdsEndpoint"
        - fromFieldPath: "status.rdsSecretName"
          toFieldPath: "spec.parameters.rdsSecretName"

    - name: github-repo
      base:
        apiVersion: jk8s.io/v1beta1
        kind: XGitHubRepo
      patches:    
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.parameters.name"
          transforms:
            - type: string
              string:
                fmt: "cluster-%s"
