---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: jk8s-cluster
spec:
  compositeTypeRef:
    apiVersion: jk8s.io/v1beta1
    kind: XCluster

  patchSets:
    - name: common-parameters
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.parameters.region"
        - fromFieldPath: "spec.parameters.environment"
          toFieldPath: "spec.parameters.environment"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.parameters.name"            

  resources:

    - name: cluster-vpc
      base:
        apiVersion: aws.jk8s.io/v1beta1
        kind: XClusterVPC
      patches:    
        - type: PatchSet
          patchSetName: common-parameters

    - name: hosted-zone
      base:
        apiVersion: jk8s.io/v1beta1
        kind: XHostedZone
      patches:    
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: "spec.parameters.fqdn"
          toFieldPath: "spec.parameters.fqdn"
        - type: ToCompositeFieldPath
          fromFieldPath: status.zoneID
          toFieldPath: status.zoneID

    - name: eks-cluster
      base:
        apiVersion: aws.jk8s.io/v1beta1
        kind: XEKSCluster
      patches:    
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.parameters.vpcName"
        - fromFieldPath: "spec.parameters.fqdn"
          toFieldPath: "spec.parameters.fqdn"
        - fromFieldPath: "status.zoneID"
          toFieldPath: "spec.parameters.hostedZoneID"


