---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: jk8s-cluster
spec:
  compositeTypeRef:
    apiVersion: jk8s.io/v1beta1
    kind: XCluster

  patchSets:
    - name: common-parameters
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.parameters.region"
        - fromFieldPath: "spec.parameters.environment.providerConfigName"
          toFieldPath: "spec.parameters.environment"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.parameters.name"            

  resources:

    - name: cluster-vpc
      base:
        apiVersion: aws.jk8s.io/v1beta1
        kind: XClusterVPC
      patches:    
        - type: PatchSet
          patchSetName: common-parameters

    - name: hosted-zone
      base:
        apiVersion: jk8s.io/v1beta1
        kind: XHostedZone
      patches:    
        - type: PatchSet
          patchSetName: common-parameters
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.name
              - fromFieldPath: spec.parameters.environment.hostedZoneName
            strategy: string
            string:
              fmt: "%s.%s"
          toFieldPath: "spec.parameters.fqdn"
          policy:
            fromFieldPath: Required            
        - type: ToCompositeFieldPath
          fromFieldPath: status.zoneID
          toFieldPath: status.zoneID
        - type: ToCompositeFieldPath
          fromFieldPath: status.delegationSet.nameServers
          toFieldPath: status.nameServers

    - name: hosted-zone-delegation
      base:
        apiVersion: route53.aws.crossplane.io/v1alpha1
        kind: ResourceRecordSet
        spec:
          forProvider:
            type: NS
            ttl: 300
          providerConfigRef:
            name: local
      patches:
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: spec.parameters.environment.hostedZoneID
          toFieldPath: spec.forProvider.zoneId
        - fromFieldPath: status.nameServers[0]
          toFieldPath: spec.forProvider.resourceRecords[0].value
        - fromFieldPath: status.nameServers[1]
          toFieldPath: spec.forProvider.resourceRecords[1].value
        - fromFieldPath: status.nameServers[2]
          toFieldPath: spec.forProvider.resourceRecords[2].value
        - fromFieldPath: status.nameServers[3]
          toFieldPath: spec.forProvider.resourceRecords[3].value
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.name
              - fromFieldPath: spec.parameters.environment.hostedZoneName
            strategy: string
            string:
              fmt: "%s.%s"
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
          policy:
            fromFieldPath: Required
    
    - name: rds-cluster
      base:
        apiVersion: jk8s.io/v1beta1
        kind: XRDSCluster
        spec:
          parameters:
            name: PATCHED
      patches:
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.parameters.vpcName"
        - fromFieldPath: spec.parameters.name
          toFieldPath: spec.parameters.name
        - type: ToCompositeFieldPath
          fromFieldPath: status.rdsSecretName
          toFieldPath: status.rdsSecretName
        - type: ToCompositeFieldPath
          fromFieldPath: status.connectionSecretName
          toFieldPath: status.rdsConnectionSecretName
        - type: ToCompositeFieldPath
          fromFieldPath: status.endpoint
          toFieldPath: status.rdsEndpoint

    - name: rds-sql-provider
      base:
        apiVersion: postgresql.sql.crossplane.io/v1alpha1
        kind: ProviderConfig
        spec:
          defaultDatabase: postgres
          credentials:
            source: PostgreSQLConnectionSecret
            connectionSecretRef:
              namespace: crossplane-system
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.name
              - fromFieldPath: spec.parameters.environment.providerConfigName
            strategy: string
            string:
              fmt: "%s-%s"
          toFieldPath: metadata.name
          policy:
            fromFieldPath: Required
        - fromFieldPath: status.rdsConnectionSecretName
          toFieldPath: spec.credentials.connectionSecretRef.name
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: status.sqlProviderConfigName

    - name: eks-cluster
      base:
        apiVersion: aws.jk8s.io/v1beta1
        kind: XEKSCluster
      patches:    
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.parameters.vpcName"
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.name
              - fromFieldPath: spec.parameters.environment.hostedZoneName
            strategy: string
            string:
              fmt: "%s.%s"
          toFieldPath: "spec.parameters.fqdn"
          policy:
            fromFieldPath: Required            
        - fromFieldPath: "status.zoneID"
          toFieldPath: "spec.parameters.hostedZoneID"
          transforms:
            - type: string
              string:
                type: TrimPrefix
                trim: '/'
        - fromFieldPath: "status.rdsEndpoint"
          toFieldPath: "spec.parameters.rdsEndpoint"
        - fromFieldPath: "status.rdsSecretName"
          toFieldPath: "spec.parameters.rdsSecretName"
        - fromFieldPath: "spec.parameters.repository.gitURL"
          toFieldPath: "spec.parameters.appsRepoURL"
        - type: ToCompositeFieldPath
          fromFieldPath: status.oidcIssuer
          toFieldPath: status.oidcIssuer
        - fromFieldPath: spec.parameters.environment.awsAccountNumber
          toFieldPath: spec.parameters.awsAccountNumber
        - fromFieldPath: spec.parameters.privateRepository.name
          toFieldPath: spec.parameters.privateRepository.name
        - fromFieldPath: spec.parameters.privateRepository.url
          toFieldPath: spec.parameters.privateRepository.url
        - fromFieldPath: spec.parameters.privateRepository.externalSecret.name
          toFieldPath: spec.parameters.privateRepository.externalSecret.name
        - type: ToCompositeFieldPath
          fromFieldPath: status.connectionSecretRefName
          toFieldPath: status.clusterConnectionSecretRefName

    - name: crossplane-kubernetes-provider
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: kubernetes.crossplane.io/v1alpha1
              kind: ProviderConfig
              spec:
                credentials:
                  source: Secret
                  secretRef:
                    namespace: crossplane-system
                    key: kubeconfig
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.name
              - fromFieldPath: spec.parameters.environment.providerConfigName
            strategy: string
            string:
              fmt: "%s-%s"
          toFieldPath: spec.forProvider.manifest.metadata.name
          policy:
            fromFieldPath: Required
        - fromFieldPath: status.clusterConnectionSecretRefName
          toFieldPath: spec.forProvider.manifest.spec.credentials.secretRef.name
          policy:
            fromFieldPath: Required
        - type: ToCompositeFieldPath
          fromFieldPath: spec.forProvider.manifest.metadata.name
          toFieldPath: status.kubernetesProviderConfigName
          
