{{ if .Values.aws.secretsManager.argocdServiceAccountName }}
{{ if .Values.aws.secretsManager.argocdServiceAccountRoleARN }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.aws.secretsManager.argocdServiceAccountName }}
  namespace: {{ .Values.argocd.namespace }}
  annotations: 
    eks.amazonaws.com/role-arn: {{ .Values.aws.secretsManager.argocdServiceAccountRoleARN }}
{{ end }}
---            
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secrets-store-aws-sm
  namespace: {{ .Values.argocd.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-southeast-2"
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.secretsManager.argocdServiceAccountName }}
{{ end }}
{{ if .Values.aws.secretsManager.telemetryServiceAccountName }}
{{ if .Values.aws.secretsManager.telemetryServiceAccountRoleARN }}
---            
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.aws.secretsManager.telemetryServiceAccountName }}
  namespace: telemetry
  annotations: 
    eks.amazonaws.com/role-arn: {{ .Values.aws.secretsManager.telemetryServiceAccountRoleARN }}
{{ end }}
---            
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secrets-store-aws-sm
  namespace: telemetry
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-southeast-2"
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.secretsManager.telemetryServiceAccountName }}
{{ end }}
{{ if .Values.aws.secretsManager.appServiceAccountName }}
{{ if .Values.aws.secretsManager.appServiceAccountRoleARN }}
---            
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.aws.secretsManager.appServiceAccountName }}
  namespace: app
  annotations: 
    eks.amazonaws.com/role-arn: {{ .Values.aws.secretsManager.appServiceAccountRoleARN }}
{{ end }}
---            
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secrets-store-aws-sm
  namespace: app
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-southeast-2"
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.secretsManager.appServiceAccountName }}
{{ end }}
{{ if .Values.aws.secretsManager.crossplaneServiceAccountName }}
{{ if .Values.aws.secretsManager.crossplaneServiceAccountRoleARN }}
---            
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.aws.secretsManager.crossplaneServiceAccountName }}
  namespace: crossplane-system
  annotations: 
    eks.amazonaws.com/role-arn: {{ .Values.aws.secretsManager.crossplaneServiceAccountRoleARN }}
{{ end }}
---            
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secrets-store-aws-sm
  namespace: crossplane-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-southeast-2"
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.secretsManager.crossplaneServiceAccountName }}
{{ end }}