{{ if .Values.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: secrets-store-aws-sm
    kind: SecretStore
  target:
    name: rds-crossplane
    creationPolicy: Owner
  dataFrom:
    - key: "{{ .Values.rdsSecretName }}"
{{ end }}{{ end }}