{{ if .Values.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: secrets-store-aws-sm
    kind: SecretStore
  target:
    name: rds
    creationPolicy: Owner
    template:
      data:
        # For use in env-vars
        POSTGRES_HOST: "{{ "{{ .endpoint | toString }}" }}"
        POSTGRES_PORT: "5432"
        POSTGRES_USERNAME: "{{ "{{ .username | toString }}" }}"
        POSTGRES_PASSWORD: "{{ "{{ .password | toString }}" }}"
  dataFrom:
    - key: "{{ .Values.rdsSecretName }}"
