# Defaults
spec:
  destination:
    server: https://kubernetes.default.svc
cluster:
  name: "in-cluster"
  awsRegion: "ap-southeast-2"
  clusterAutoscaler:
    namespace: "kube-system"

# External Secrets
enabled: false
rdsSecretName: ""
aws:
  secretsManager:
    argocdServiceAccountName: external-secrets
    telemetryServiceAccountName: external-secrets
    appServiceAccountName: external-secrets
    crossplaneServiceAccountName: external-secrets
    argocdServiceAccountRoleARN:
    telemetryServiceAccountRoleARN:
    appServiceAccountRoleARN:
    crossplaneServiceAccountRoleARN:
argocd:
  namespace: ""

# Dependencies
external-secrets:
  installCRDs: true
