apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-vs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hosts:
    - "prometheus.{{ .Values.dns.fqdn }}"
  gateways:
    - istio-ingress/ingress-gateway
  http:
    - route:
        - destination:
            host: prometheus-kube-prometheus-prometheus
            port:
              number: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  host: prometheus-kube-prometheus-prometheus
  trafficPolicy:
    tls:
      mode: DISABLE
---

