---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: jk8s-cluster-set
spec:

  compositeTypeRef:
    apiVersion: jk8s.io/v1beta1
    kind: XClusterSet

  patchSets:
    - name: common-parameters
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.parameters.region"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.parameters.name"

  resources:

    # 
    # Prod
    #

    - name: prod-cluster
      base:
        apiVersion: jk8s.io/v1beta1
        kind: XCluster
        spec:
          parameters:
            environment:
              providerConfigName: prod
      patches:
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: "spec.parameters.environments.production.hostedZoneID"
          toFieldPath: "spec.parameters.environment.hostedZoneID"
        - fromFieldPath: "spec.parameters.environments.production.hostedZoneName"
          toFieldPath: "spec.parameters.environment.hostedZoneName"
        
    #
    # Dev
    #

    - name: dev-cluster
      base:
        apiVersion: jk8s.io/v1beta1
        kind: XCluster
        spec:
          parameters:
            environment:
              providerConfigName: dev
      patches:
        - type: PatchSet
          patchSetName: common-parameters
        - fromFieldPath: "spec.parameters.environments.development.hostedZoneID"
          toFieldPath: "spec.parameters.environment.hostedZoneID"
        - fromFieldPath: "spec.parameters.environments.development.hostedZoneName"
          toFieldPath: "spec.parameters.environment.hostedZoneName"
