---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclustersets.jk8s.io
spec:
  group: jk8s.io
  names:
    kind: XClusterSet
    plural: xclustersets
  versions:
  - name: v1beta1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    description: Name of the Cluster Set
                    type: string       
                  region:
                    description: Region to deploy into
                    type: string       
                    enum: [ap-southeast-2]
                    default: ap-southeast-2
                  environments:
                    type: object
                    properties:
                      development: 
                        type: object
                        properties: 
                          hostedZoneID:
                            type: string
                            description: The ID of an existing hosted zone for the development environment
                          hostedZoneName:
                            type: string
                            description: The name of an existing hosted zone for the development environment
                          awsAccountNumber:
                            type: integer
                            description: The AWS account number for the development environment
                          awsRegion:
                            type: string
                            description: The AWS region for the development environment
                        required:
                          - hostedZoneID
                          - hostedZoneName
                      production: 
                        type: object
                        properties: 
                          hostedZoneID:
                            type: string
                            description: The ID of an existing hosted zone for the production environment
                          hostedZoneName:
                            type: string
                            description: The name of an existing hosted zone for the production environment
                          awsAccountNumber:
                            type: integer
                            description: The AWS account number for the production environment
                          awsRegion:
                            type: string
                            description: The AWS region for the production environment
                        required:
                          - hostedZoneID
                          - hostedZoneName
                    required:
                      - development
                      - production
                  repository:
                    type: object
                    properties: 
                      owner:
                        type: string
                        description: The owner of the cluster's GitHub Repo
                      org:
                        type: string
                        description: The organization to add the GitHub Repo to
                    required:
                      - owner
                  privateRepository:
                    type: object
                    description: Private GitHub repo and credentials
                    properties:
                      name: 
                        type: string
                        description: Name of the GitHub Repo
                      url:
                        type: string
                        description: URL for the GitHub Repo
                      externalSecret:
                        type: object
                        description: Use external secrets to get token
                        properties:
                          name: 
                            type: string
                            description: The name of the external secret that contains the GitHub token for accessing this private repo
                    required:
                      - name
                      - url
                required:
                  - name
                  - environments
                  - repository
            required:
              - parameters
          status:
            type: object
            properties:
              repository:
                type: object
                properties:
                  gitURL:
                    type: string
                  htmlURL:
                    type: string
                  name: 
                    type: string
              environments:
                type: object
                properties:
                  development:
                    type: object
                    properties:
                      kubernetesProviderConfigName:
                        type: string
                      sqlProviderConfigName:
                        type: string
                  production:
                    type: object
                    properties:
                      kubernetesProviderConfigName:
                        type: string
                      sqlProviderConfigName:
                        type: string
