---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xhostedzones.jk8s.io
spec:
  group: jk8s.io
  names:
    kind: XHostedZone
    plural: xhostedzones
  connectionSecretKeys:
    - zone-id
  versions:
  - name: v1beta1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  fqdn:
                    description: The FQDN for this Hosted Zone
                    type: string       
                  environment:
                    description: The deployment environment
                    type: string

                required:
                  - fqdn
                  - environment
            required:
              - parameters
          status:
            type: object 
            properties:
              zoneID:
                type: string
