apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-kubernetes-debug-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  args:
    - --debug
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: "crossplane/provider-kubernetes:main"
  controllerConfigRef:
    name: provider-kubernetes-debug-config
