{{ $server := .Values.spec.destination.server  }}
{{ $fqdn := .Values.dns.fqdn }}
{{ $argocdNamespace := .Values.argocd.namespace }}
{{ range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .name }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .repoURL }}"
    {{- if .targetRevision }}
    targetRevision: "{{ .targetRevision }}"
    {{- end }}
    {{- if .path }}
    path: "{{ .path }}"
    {{- end }}
    {{- if .chart }}
    chart: "{{ .chart }}"
    {{- end }}
    helm:
      parameters:
        - name: argocd.namespace
          value: "{{ $argocdNamespace }}"
      values:
        {{ toYaml .values | nindent 8 }}
  destination:
    namespace: "app"
    server: "{{ $server }}"
  syncPolicy:
    automated:
      prune: true
{{ end }}