apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
  labels:
    istio-injection: disabled
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---    
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.repository.url }}"
    targetRevision: "{{ .Values.repository.targetRevision }}"
    path: "{{ .Values.repository.appsPath }}/crossplane"
  destination:
    namespace: crossplane-system
    server: "{{ .Values.spec.destination.server }}"
  syncPolicy:
    automated:
      prune: true
