{{ if .Values.secrets.externalSecrets.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    istio-injection: disabled
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: default
  source:
    repoURL: {{ .Values.repository.url }}
    targetRevision: {{ .Values.repository.targetRevision }}
    path: "{{ .Values.repository.appsPath }}/external-secrets"
    helm:
      parameters:
        - name: argocd.namespace
          value: {{ .Values.argocd.namespace }}
        - name: enabled
          value: "{{ .Values.secrets.externalSecrets.enabled }}"
        - name: rdsSecretName
          value: {{ .Values.secrets.externalSecrets.rdsSecretName }}
        {{ if .Values.secrets.externalSecrets.aws.secretsManager.argocdServiceAccountName }}
        - name: aws.secretsManager.argocdServiceAccountName
          value: {{ .Values.secrets.externalSecrets.aws.secretsManager.argocdServiceAccountName }}
        {{ end }}
        {{ if .Values.secrets.externalSecrets.aws.secretsManager.telemetryServiceAccountName }}
        - name: aws.secretsManager.telemetryServiceAccountName
          value: {{ .Values.secrets.externalSecrets.aws.secretsManager.telemetryServiceAccountName }}
        {{ end }}
        {{ if .Values.secrets.externalSecrets.aws.secretsManager.appServiceAccountName }}
        - name: aws.secretsManager.appServiceAccountName
          value: {{ .Values.secrets.externalSecrets.aws.secretsManager.appServiceAccountName }}
        {{ end }}
        {{ if .Values.secrets.externalSecrets.aws.secretsManager.crossplaneServiceAccountName }}
        - name: aws.secretsManager.crossplaneServiceAccountName
          value: {{ .Values.secrets.externalSecrets.aws.secretsManager.crossplaneServiceAccountName }}
        {{ end }}
        - name: aws.secretsManager.argocdServiceAccountRoleARN
          value: {{ .Values.secrets.externalSecrets.aws.secretsManager.argocdServiceAccountRoleARN }}
        - name: aws.secretsManager.telemetryServiceAccountRoleARN
          value: {{ .Values.secrets.externalSecrets.aws.secretsManager.telemetryServiceAccountRoleARN }}
        - name: aws.secretsManager.appServiceAccountRoleARN
          value: {{ .Values.secrets.externalSecrets.aws.secretsManager.appServiceAccountRoleARN }}
        - name: aws.secretsManager.crossplaneServiceAccountRoleARN
          value: {{ .Values.secrets.externalSecrets.aws.secretsManager.crossplaneServiceAccountRoleARN }}
  destination:
    namespace: external-secrets
    server: "{{ .Values.spec.destination.server }}"
  syncPolicy:
    automated:
      prune: true
{{ end }}
